C: copyright notice
letsblockit/letsblockit pull request #211
Opened 2022-07-05 06:03 UTC by JohnyP36

In the old youtube layout they changed the source code of the copyright notice. Therefore the rule needs to be changed.

See `https://www.youtube.com/watch?v=WYU4fBQVVOY` 

<details><summary>Screenshot</summary> 

![image](https://user-images.githubusercontent.com/81161435/177260098-2d5391ce-23ef-4a47-bf5f-4a5410226d66.png)

</details>

2022-07-06 19:16 UTC, xvello requested changes
Thanks @JohnyP36, two comments on this change.

Also, do you think we should keep the old filter for a while? I'm a bit confused as this is a new version of the old layout? How come you're not on the "new" layout?

2022-07-06 19:16 UTC, xvello commented on data/filters/youtube-cleanup.yaml
> +    www.youtube.com##[class*="video-secondary-info-renderer"] > #items:has(.ytd-video-description-music-section-renderer)
Bad identation
```suggestion
  www.youtube.com##[class*="video-secondary-info-renderer"] > #items:has(.ytd-video-description-music-section-renderer)
```

2022-07-06 19:16 UTC, xvello commented on data/filters/youtube-cleanup.yaml
> +    www.youtube.com##[class*="video-secondary-info-renderer"] > #items:has(.ytd-video-description-music-section-renderer)
You'll need to update the corresponding test, line 80

2022-07-07 06:00 UTC, JohnyP36 commented
> Thanks @JohnyP36, two comments on this change.
> 
> Also, do you think we should keep the old filter for a while? I'm a bit confused as this is a new version of the old layout? How come you're not on the "new" layout?

Maybe it's better to also keep the old filter for a while. I have put it back. 

I don't know why I'm still on the old layout and not the "new" layout. Maybe it has to do with the fact that YouTube is still testing it and the new layout is rolling out in stages.

2022-07-07 10:42 UTC, xvello approved these changes
Thanks a lot!

2022-07-07 10:43 UTC, merged